# Generated by Django 4.2.9 on 2024-02-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Repuestos',
        ),
    ]
