# Generated by Django 4.2.9 on 2024-02-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_curso_repuestos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repuestos',
            new_name='Cursos',
        ),
    ]
