# Generated by Django 4.2.9 on 2024-02-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_rename_apellido_profesor_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='maquina',
            new_name='nombre',
        ),
    ]
