# Generated by Django 4.2.9 on 2024-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_rename_maquina_profesor_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Maquina',
        ),
    ]
