# Generated by Django 4.2.9 on 2024-03-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitarRepuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha_solicitud', models.DateField()),
            ],
        ),
    ]
